dependencies:
  cupertino_icons: ^1.0.3
  effective_dart: ^1.3.1
  flutter:
    sdk: flutter
  lint: ^1.5.3
  pedantic: ^1.11.0
  provider: ^5.0.0
description: A new Flutter project.
dev_dependencies:
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=2.12.0 <3.0.0'
flutter:
  fonts:
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
  uses-material-design: true
name: flutter_shopping_app
publish_to: none
version: 1.0.0+1
